---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: REPLACE_WITH_YOUR_DESIRED_USERNAME
 namespace: REPLACE_WITH_YOUR_DESIRED_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: REPLACE_WITH_YOUR_DESIRED_USERNAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: REPLACE_WITH_YOUR_DESIRED_USERNAME
  namespace: REPLACE_WITH_YOUR_DESIRED_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: REPLACE_WITH_YOUR_DESIRED_USERNAME
  namespace: REPLACE_WITH_YOUR_DESIRED_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: REPLACE_WITH_YOUR_DESIRED_USERNAME
  namespace: REPLACE_WITH_YOUR_DESIRED_NAMESPACE
